### ISSUE TITLE
The ability to provide an Amazon product link and an email address

### ISSUE THREAD

**Issue by sogwiz** [simonshm5/amazon-webscraper#1]
If this program could take in a couple different arguments, then it would be pretty neat! 

- amazon product link: Here, I'd give the landing page to an amazon product link that I'd like scraped
- email address: Here, I'd supply the email address I'd like the notification to be sent to

**Comment by simonshampoo** [comment]
Thank you for your wonderful suggestions! That's definitely something I aim on doing soon. I aim to give it more functionality with a low-cost GUI that you can run in the background while using your computer--functional while in sleep mode as well.

**Comment by sogwiz** [comment]
Avit bassima rabba (thank you very much)
