### ISSUE TITLE
README file

### ISSUE THREAD

**Issue by sogwiz** [simonshm5/amazon-webscraper#2]
It would be nice to be able to execute this script by following a set of instructions in a README file.  
Nice to have: Would it make sense to have this run as a docker container?

**Comment by simonshampoo** [comment]
A concise and effective README is definitely vital to a project. I will definitely add one ASAP. 
After reading about docker containers, absolutely--this functionality should always be consistent from machine to machine.

**Comment by sogwiz** [comment]
Thank you
